// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Task_20_WepApi5.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int Amount { get; set; }

    public string Description { get; set; }

    public int CategoryId { get; set; }

    public string image { get; set; }
    [JsonIgnore]
    public virtual Category category { get; set; }
}